k9s:
  disablePodCounting: false
  imageScans:
    enable: false
    exclusions:
      labels: {}
      namespaces: []
  liveViewAutoRefresh: false
  logger:
    buffer: 5000
    showTime: false
    sinceSeconds: -1
    tail: 100
    textWrap: false
  maxConnRetry: 5
  noExitOnCtrlC: false
  readOnly: false
  refreshRate: 2
  shellPod:
    image: busybox:1.35.0
    limits:
      cpu: 100m
      memory: 100Mi
    namespace: default
  skipLatestRevCheck: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  ui:
    crumbsless: false
    defaultsToFullScreen: false
    enableMouse: false
    headless: false
    logoless: true
    noIcons: false
    reactive: false
    skin: everforest
